
package com.management.ws.server.pallet;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecWMSServerService", targetNamespace = "http://upwms.cxf.xhwcs.shengmo.com/", wsdlLocation = "http://141.168.1.108:8081/ncsmwcs/ws/recWMSInfo?wsdl")
public class RecWMSServerService
    extends Service
{

    private final static URL RECWMSSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECWMSSERVERSERVICE_EXCEPTION;
    private final static QName RECWMSSERVERSERVICE_QNAME = new QName("http://upwms.cxf.xhwcs.shengmo.com/", "RecWMSServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://141.168.1.108:8081/ncsmwcs/ws/recWMSInfo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECWMSSERVERSERVICE_WSDL_LOCATION = url;
        RECWMSSERVERSERVICE_EXCEPTION = e;
    }

    public RecWMSServerService() {
        super(__getWsdlLocation(), RECWMSSERVERSERVICE_QNAME);
    }

    public RecWMSServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECWMSSERVERSERVICE_QNAME, features);
    }

    public RecWMSServerService(URL wsdlLocation) {
        super(wsdlLocation, RECWMSSERVERSERVICE_QNAME);
    }

    public RecWMSServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECWMSSERVERSERVICE_QNAME, features);
    }

    public RecWMSServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecWMSServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecWMSServer
     */
    @WebEndpoint(name = "RecWMSServerPort")
    public RecWMSServer getRecWMSServerPort() {
        return super.getPort(new QName("http://upwms.cxf.xhwcs.shengmo.com/", "RecWMSServerPort"), RecWMSServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecWMSServer
     */
    @WebEndpoint(name = "RecWMSServerPort")
    public RecWMSServer getRecWMSServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://upwms.cxf.xhwcs.shengmo.com/", "RecWMSServerPort"), RecWMSServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECWMSSERVERSERVICE_EXCEPTION!= null) {
            throw RECWMSSERVERSERVICE_EXCEPTION;
        }
        return RECWMSSERVERSERVICE_WSDL_LOCATION;
    }

}
