<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://upwms.cxf.xhwcs.shengmo.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="RecWMSServerService" targetNamespace="http://upwms.cxf.xhwcs.shengmo.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://upwms.cxf.xhwcs.shengmo.com/" elementFormDefault="unqualified" targetNamespace="http://upwms.cxf.xhwcs.shengmo.com/" version="1.0">

  <xs:element name="recWMSHandleInfo" type="tns:recWMSHandleInfo"/>

  <xs:element name="recWMSHandleInfoResponse" type="tns:recWMSHandleInfoResponse"/>

  <xs:complexType name="recWMSHandleInfo">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="recWMSHandleInfoResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="recWMSHandleInfo">
    <wsdl:part element="tns:recWMSHandleInfo" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="recWMSHandleInfoResponse">
    <wsdl:part element="tns:recWMSHandleInfoResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="RecWMSServer">
    <wsdl:operation name="recWMSHandleInfo">
      <wsdl:input message="tns:recWMSHandleInfo" name="recWMSHandleInfo">
    </wsdl:input>
      <wsdl:output message="tns:recWMSHandleInfoResponse" name="recWMSHandleInfoResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RecWMSServerServiceSoapBinding" type="tns:RecWMSServer">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="recWMSHandleInfo">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="recWMSHandleInfo">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="recWMSHandleInfoResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RecWMSServerService">
    <wsdl:port binding="tns:RecWMSServerServiceSoapBinding" name="RecWMSServerPort">
      <soap:address location="http://141.168.1.108:8081/ncsmwcs/ws/recWMSInfo"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>