
package com.management.ws.server.pallet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RecWMSServer", targetNamespace = "http://upwms.cxf.xhwcs.shengmo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecWMSServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recWMSHandleInfo", targetNamespace = "http://upwms.cxf.xhwcs.shengmo.com/", className = "com.management.ws.server.pallet.RecWMSHandleInfo")
    @ResponseWrapper(localName = "recWMSHandleInfoResponse", targetNamespace = "http://upwms.cxf.xhwcs.shengmo.com/", className = "com.management.ws.server.pallet.RecWMSHandleInfoResponse")
    public String recWMSHandleInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
