
package com.management.ws.server.reply;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IReceiveReply", targetNamespace = "http://ws.management.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IReceiveReply {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pallectReply", targetNamespace = "http://ws.management.com/", className = "com.management.ws.server.reply.PallectReply")
    @ResponseWrapper(localName = "pallectReplyResponse", targetNamespace = "http://ws.management.com/", className = "com.management.ws.server.reply.PallectReplyResponse")
    public String pallectReply(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
