
package com.management.ws.server.reply;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReceiveReplyImplService", targetNamespace = "http://ws.management.com/", wsdlLocation = "http://localhost:8080/management/ws/receiveReply?wsdl")
public class ReceiveReplyImplService
    extends Service
{

    private final static URL RECEIVEREPLYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RECEIVEREPLYIMPLSERVICE_EXCEPTION;
    private final static QName RECEIVEREPLYIMPLSERVICE_QNAME = new QName("http://ws.management.com/", "ReceiveReplyImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/management/ws/receiveReply?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECEIVEREPLYIMPLSERVICE_WSDL_LOCATION = url;
        RECEIVEREPLYIMPLSERVICE_EXCEPTION = e;
    }

    public ReceiveReplyImplService() {
        super(__getWsdlLocation(), RECEIVEREPLYIMPLSERVICE_QNAME);
    }

    public ReceiveReplyImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECEIVEREPLYIMPLSERVICE_QNAME, features);
    }

    public ReceiveReplyImplService(URL wsdlLocation) {
        super(wsdlLocation, RECEIVEREPLYIMPLSERVICE_QNAME);
    }

    public ReceiveReplyImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECEIVEREPLYIMPLSERVICE_QNAME, features);
    }

    public ReceiveReplyImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReceiveReplyImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IReceiveReply
     */
    @WebEndpoint(name = "ReceiveReplyImplPort")
    public IReceiveReply getReceiveReplyImplPort() {
        return super.getPort(new QName("http://ws.management.com/", "ReceiveReplyImplPort"), IReceiveReply.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IReceiveReply
     */
    @WebEndpoint(name = "ReceiveReplyImplPort")
    public IReceiveReply getReceiveReplyImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.management.com/", "ReceiveReplyImplPort"), IReceiveReply.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECEIVEREPLYIMPLSERVICE_EXCEPTION!= null) {
            throw RECEIVEREPLYIMPLSERVICE_EXCEPTION;
        }
        return RECEIVEREPLYIMPLSERVICE_WSDL_LOCATION;
    }

}
